services:
  - type: web
    name: sparta-tweets
    env: python
    plan: free
    workingDir: /opt/render/project
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
